[profile.default]
src = "foundry/src"
out = "foundry/out"
libs = ["lib"]
test = "foundry/test"
script = "foundry/script"
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]

[profile.ci]
verbosity = 4

[rpc_endpoints]
moonbase = "${MOONBASE_RPC_URL}"

[etherscan]
moonbase = { key = "${MOONSCAN_API_KEY}", url = "https://api-moonbase.moonscan.io/" } 